- name: Build CMake
# You may pin to the exact commit or the version.
# uses: ashutoshvarma/action-cmake-build@0fbeeac8b1f9c8aef99e9eae9d78529ed3b0364b
uses: ashutoshvarma/action-cmake-build@v1
with:
  # Build directory where build files will be generated
  build-dir: ${{ runner.workspace }}/build
  # CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)
  build-type: Release
          
